// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhn3uIHs7Jhm6T1glooULknQsQdnNv4s',
    appId: '1:486760701872:web:245a32ef776ddcca2cc075',
    messagingSenderId: '486760701872',
    projectId: 'sadafarts-f59d8',
    authDomain: 'sadafarts-f59d8.firebaseapp.com',
    storageBucket: 'sadafarts-f59d8.appspot.com',
    measurementId: 'G-F5XJNLLWDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NgNddDV3slxuoSeSyQaTyVZxhKG_JOs',
    appId: '1:486760701872:android:a5d5ddef88d293bf2cc075',
    messagingSenderId: '486760701872',
    projectId: 'sadafarts-f59d8',
    storageBucket: 'sadafarts-f59d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPoaXmTnHu28KUVcmzKzyUnrFgLA9hx4s',
    appId: '1:486760701872:ios:4fa80a8edcfacbaf2cc075',
    messagingSenderId: '486760701872',
    projectId: 'sadafarts-f59d8',
    storageBucket: 'sadafarts-f59d8.appspot.com',
    iosBundleId: 'com.example.arts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPoaXmTnHu28KUVcmzKzyUnrFgLA9hx4s',
    appId: '1:486760701872:ios:4fa80a8edcfacbaf2cc075',
    messagingSenderId: '486760701872',
    projectId: 'sadafarts-f59d8',
    storageBucket: 'sadafarts-f59d8.appspot.com',
    iosBundleId: 'com.example.arts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhn3uIHs7Jhm6T1glooULknQsQdnNv4s',
    appId: '1:486760701872:web:08462e090d7e01522cc075',
    messagingSenderId: '486760701872',
    projectId: 'sadafarts-f59d8',
    authDomain: 'sadafarts-f59d8.firebaseapp.com',
    storageBucket: 'sadafarts-f59d8.appspot.com',
    measurementId: 'G-21847M2N4S',
  );
}
